//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PathLocalDB {
            get {
                return ((bool)(this["PathLocalDB"]));
            }
            set {
                this["PathLocalDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathLoNaDB {
            get {
                return ((string)(this["PathLoNaDB"]));
            }
            set {
                this["PathLoNaDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBName {
            get {
                return ((string)(this["DBName"]));
            }
            set {
                this["DBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlUserName {
            get {
                return ((string)(this["SqlUserName"]));
            }
            set {
                this["SqlUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlPassword {
            get {
                return ((string)(this["SqlPassword"]));
            }
            set {
                this["SqlPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Mode {
            get {
                return ((string)(this["Mode"]));
            }
            set {
                this["Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerName {
            get {
                return ((string)(this["ServerName"]));
            }
            set {
                this["ServerName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnType {
            get {
                return ((string)(this["ConnType"]));
            }
            set {
                this["ConnType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProductTrue {
            get {
                return ((string)(this["ProductTrue"]));
            }
            set {
                this["ProductTrue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProductBeginDate {
            get {
                return ((string)(this["ProductBeginDate"]));
            }
            set {
                this["ProductBeginDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProductEndDate {
            get {
                return ((string)(this["ProductEndDate"]));
            }
            set {
                this["ProductEndDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المخزن {
            get {
                return ((bool)(this["المخزن"]));
            }
            set {
                this["المخزن"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool اعدادات_النظام {
            get {
                return ((bool)(this["اعدادات_النظام"]));
            }
            set {
                this["اعدادات_النظام"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool التقارير {
            get {
                return ((bool)(this["التقارير"]));
            }
            set {
                this["التقارير"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool اعدادات_الاتصال {
            get {
                return ((bool)(this["اعدادات_الاتصال"]));
            }
            set {
                this["اعدادات_الاتصال"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool معلومات_الشركة {
            get {
                return ((bool)(this["معلومات_الشركة"]));
            }
            set {
                this["معلومات_الشركة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool العمليات {
            get {
                return ((bool)(this["العمليات"]));
            }
            set {
                this["العمليات"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المعلمين {
            get {
                return ((bool)(this["المعلمين"]));
            }
            set {
                this["المعلمين"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الخياطون {
            get {
                return ((bool)(this["الخياطون"]));
            }
            set {
                this["الخياطون"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool العملاء {
            get {
                return ((bool)(this["العملاء"]));
            }
            set {
                this["العملاء"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ترميز_المقاسات {
            get {
                return ((bool)(this["ترميز_المقاسات"]));
            }
            set {
                this["ترميز_المقاسات"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool تصنيفات_الاقمشة {
            get {
                return ((bool)(this["تصنيفات_الاقمشة"]));
            }
            set {
                this["تصنيفات_الاقمشة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الاقمشة {
            get {
                return ((bool)(this["الاقمشة"]));
            }
            set {
                this["الاقمشة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool سندات_القبض {
            get {
                return ((bool)(this["سندات_القبض"]));
            }
            set {
                this["سندات_القبض"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المشتريات {
            get {
                return ((bool)(this["المشتريات"]));
            }
            set {
                this["المشتريات"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool شاشة_التوريد {
            get {
                return ((bool)(this["شاشة_التوريد"]));
            }
            set {
                this["شاشة_التوريد"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool اشعارات_دائنه {
            get {
                return ((bool)(this["اشعارات_دائنه"]));
            }
            set {
                this["اشعارات_دائنه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فاتورة_التفصيل {
            get {
                return ((bool)(this["فاتورة_التفصيل"]));
            }
            set {
                this["فاتورة_التفصيل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool اشعارات_SMS {
            get {
                return ((bool)(this["اشعارات_SMS"]));
            }
            set {
                this["اشعارات_SMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقرير_الفترة {
            get {
                return ((bool)(this["تقرير_الفترة"]));
            }
            set {
                this["تقرير_الفترة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_للفترة {
            get {
                return ((bool)(this["الفواتير_للفترة"]));
            }
            set {
                this["الفواتير_للفترة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المستخدمون_والمجموعات {
            get {
                return ((bool)(this["المستخدمون_والمجموعات"]));
            }
            set {
                this["المستخدمون_والمجموعات"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الصلاحيات {
            get {
                return ((bool)(this["ادارة_الصلاحيات"]));
            }
            set {
                this["ادارة_الصلاحيات"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقارير_المعلمين {
            get {
                return ((bool)(this["تقارير_المعلمين"]));
            }
            set {
                this["تقارير_المعلمين"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقارير_الخياطين {
            get {
                return ((bool)(this["تقارير_الخياطين"]));
            }
            set {
                this["تقارير_الخياطين"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقارير_سندات_القبض {
            get {
                return ((bool)(this["تقارير_سندات_القبض"]));
            }
            set {
                this["تقارير_سندات_القبض"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقارير_المبيعات {
            get {
                return ((bool)(this["تقارير_المبيعات"]));
            }
            set {
                this["تقارير_المبيعات"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقارير_المشتريات {
            get {
                return ((bool)(this["تقارير_المشتريات"]));
            }
            set {
                this["تقارير_المشتريات"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool تقارير_المصروفات {
            get {
                return ((bool)(this["تقارير_المصروفات"]));
            }
            set {
                this["تقارير_المصروفات"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool تقارير_حالة_فواتير_المبيعات {
            get {
                return ((bool)(this["تقارير_حالة_فواتير_المبيعات"]));
            }
            set {
                this["تقارير_حالة_فواتير_المبيعات"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool تقرير_المخزون {
            get {
                return ((bool)(this["تقرير_المخزون"]));
            }
            set {
                this["تقرير_المخزون"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool تقارير_حسابات_العملاء {
            get {
                return ((bool)(this["تقارير_حسابات_العملاء"]));
            }
            set {
                this["تقارير_حسابات_العملاء"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool مجموعات_المستخدمين {
            get {
                return ((bool)(this["مجموعات_المستخدمين"]));
            }
            set {
                this["مجموعات_المستخدمين"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool المستخدمين {
            get {
                return ((bool)(this["المستخدمين"]));
            }
            set {
                this["المستخدمين"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفروع {
            get {
                return ((bool)(this["الفروع"]));
            }
            set {
                this["الفروع"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SkinName {
            get {
                return ((string)(this["SkinName"]));
            }
            set {
                this["SkinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PaletteName {
            get {
                return ((string)(this["PaletteName"]));
            }
            set {
                this["PaletteName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 12pt")]
        public global::System.Drawing.Font SystemFont {
            get {
                return ((global::System.Drawing.Font)(this["SystemFont"]));
            }
            set {
                this["SystemFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الموديلات_طباعة {
            get {
                return ((bool)(this["الموديلات_طباعة"]));
            }
            set {
                this["الموديلات_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المعلمين_اضافه {
            get {
                return ((bool)(this["المعلمين_اضافه"]));
            }
            set {
                this["المعلمين_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المعلمين_تعديل {
            get {
                return ((bool)(this["المعلمين_تعديل"]));
            }
            set {
                this["المعلمين_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المعلمين_حذف {
            get {
                return ((bool)(this["المعلمين_حذف"]));
            }
            set {
                this["المعلمين_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المعلمين_طباعة {
            get {
                return ((bool)(this["المعلمين_طباعة"]));
            }
            set {
                this["المعلمين_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الخياطون_اضافه {
            get {
                return ((bool)(this["الخياطون_اضافه"]));
            }
            set {
                this["الخياطون_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الخياطون_تعديل {
            get {
                return ((bool)(this["الخياطون_تعديل"]));
            }
            set {
                this["الخياطون_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الخياطون_حذف {
            get {
                return ((bool)(this["الخياطون_حذف"]));
            }
            set {
                this["الخياطون_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الخياطون_طباعة {
            get {
                return ((bool)(this["الخياطون_طباعة"]));
            }
            set {
                this["الخياطون_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool التقرير_الشهري {
            get {
                return ((bool)(this["التقرير_الشهري"]));
            }
            set {
                this["التقرير_الشهري"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool التقرير_اليومي {
            get {
                return ((bool)(this["التقرير_اليومي"]));
            }
            set {
                this["التقرير_اليومي"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool بيانات_العملاء {
            get {
                return ((bool)(this["بيانات_العملاء"]));
            }
            set {
                this["بيانات_العملاء"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_المدفوعة {
            get {
                return ((bool)(this["الفواتير_المدفوعة"]));
            }
            set {
                this["الفواتير_المدفوعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ترميز_المقاسات_اضافه {
            get {
                return ((bool)(this["ترميز_المقاسات_اضافه"]));
            }
            set {
                this["ترميز_المقاسات_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ترميز_المقاسات_تعديل {
            get {
                return ((bool)(this["ترميز_المقاسات_تعديل"]));
            }
            set {
                this["ترميز_المقاسات_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ترميز_المقاسات_حذف {
            get {
                return ((bool)(this["ترميز_المقاسات_حذف"]));
            }
            set {
                this["ترميز_المقاسات_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ترميز_المقاسات_طباعة {
            get {
                return ((bool)(this["ترميز_المقاسات_طباعة"]));
            }
            set {
                this["ترميز_المقاسات_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تصنيفات_الاقمشة_اضافه {
            get {
                return ((bool)(this["تصنيفات_الاقمشة_اضافه"]));
            }
            set {
                this["تصنيفات_الاقمشة_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تصنيفات_الاقمشة_تعديل {
            get {
                return ((bool)(this["تصنيفات_الاقمشة_تعديل"]));
            }
            set {
                this["تصنيفات_الاقمشة_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تصنيفات_الاقمشة_حذف {
            get {
                return ((bool)(this["تصنيفات_الاقمشة_حذف"]));
            }
            set {
                this["تصنيفات_الاقمشة_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تصنيفات_الاقمشة_طباعة {
            get {
                return ((bool)(this["تصنيفات_الاقمشة_طباعة"]));
            }
            set {
                this["تصنيفات_الاقمشة_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الاقمشة_اضافه {
            get {
                return ((bool)(this["الاقمشة_اضافه"]));
            }
            set {
                this["الاقمشة_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الاقمشة_تعديل {
            get {
                return ((bool)(this["الاقمشة_تعديل"]));
            }
            set {
                this["الاقمشة_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الاقمشة_حذف {
            get {
                return ((bool)(this["الاقمشة_حذف"]));
            }
            set {
                this["الاقمشة_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الاقمشة_طباعة {
            get {
                return ((bool)(this["الاقمشة_طباعة"]));
            }
            set {
                this["الاقمشة_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool سندات_الصرف_للموردين_اضافه {
            get {
                return ((bool)(this["سندات_الصرف_للموردين_اضافه"]));
            }
            set {
                this["سندات_الصرف_للموردين_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool سندات_الصرف_للموردين_تعديل {
            get {
                return ((bool)(this["سندات_الصرف_للموردين_تعديل"]));
            }
            set {
                this["سندات_الصرف_للموردين_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool سندات_الصرف_للموردين_حذف {
            get {
                return ((bool)(this["سندات_الصرف_للموردين_حذف"]));
            }
            set {
                this["سندات_الصرف_للموردين_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool سندات_الصرف_للموردين_طباعة {
            get {
                return ((bool)(this["سندات_الصرف_للموردين_طباعة"]));
            }
            set {
                this["سندات_الصرف_للموردين_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_المستلمة {
            get {
                return ((bool)(this["الفواتير_المستلمة"]));
            }
            set {
                this["الفواتير_المستلمة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool لم_يدفع_عربون {
            get {
                return ((bool)(this["لم_يدفع_عربون"]));
            }
            set {
                this["لم_يدفع_عربون"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool سند_صرف_مصروف_حذف {
            get {
                return ((bool)(this["سند_صرف_مصروف_حذف"]));
            }
            set {
                this["سند_صرف_مصروف_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool سند_صرف_مصروف_طباعة {
            get {
                return ((bool)(this["سند_صرف_مصروف_طباعة"]));
            }
            set {
                this["سند_صرف_مصروف_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool شاشة_التوريد_اضافه {
            get {
                return ((bool)(this["شاشة_التوريد_اضافه"]));
            }
            set {
                this["شاشة_التوريد_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool شاشة_التوريد_تعديل {
            get {
                return ((bool)(this["شاشة_التوريد_تعديل"]));
            }
            set {
                this["شاشة_التوريد_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool شاشة_التوريد_حذف {
            get {
                return ((bool)(this["شاشة_التوريد_حذف"]));
            }
            set {
                this["شاشة_التوريد_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool شاشة_التوريد_طباعة {
            get {
                return ((bool)(this["شاشة_التوريد_طباعة"]));
            }
            set {
                this["شاشة_التوريد_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool طلبات_التفصيل_اضافه {
            get {
                return ((bool)(this["طلبات_التفصيل_اضافه"]));
            }
            set {
                this["طلبات_التفصيل_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool طلبات_التفصيل_تعديل {
            get {
                return ((bool)(this["طلبات_التفصيل_تعديل"]));
            }
            set {
                this["طلبات_التفصيل_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool طلبات_التفصيل_حذف {
            get {
                return ((bool)(this["طلبات_التفصيل_حذف"]));
            }
            set {
                this["طلبات_التفصيل_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool طلبات_التفصيل_طباعة {
            get {
                return ((bool)(this["طلبات_التفصيل_طباعة"]));
            }
            set {
                this["طلبات_التفصيل_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فاتورة_التفصيل_اضافه {
            get {
                return ((bool)(this["فاتورة_التفصيل_اضافه"]));
            }
            set {
                this["فاتورة_التفصيل_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فاتورة_التفصيل_تعديل {
            get {
                return ((bool)(this["فاتورة_التفصيل_تعديل"]));
            }
            set {
                this["فاتورة_التفصيل_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فاتورة_التفصيل_حذف {
            get {
                return ((bool)(this["فاتورة_التفصيل_حذف"]));
            }
            set {
                this["فاتورة_التفصيل_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فاتورة_التفصيل_طباعة {
            get {
                return ((bool)(this["فاتورة_التفصيل_طباعة"]));
            }
            set {
                this["فاتورة_التفصيل_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فاتورة_جديدة_اضافه {
            get {
                return ((bool)(this["فاتورة_جديدة_اضافه"]));
            }
            set {
                this["فاتورة_جديدة_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فاتوره_جديده_تعديل {
            get {
                return ((bool)(this["فاتوره_جديده_تعديل"]));
            }
            set {
                this["فاتوره_جديده_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فاتورة_جديدة_حذف {
            get {
                return ((bool)(this["فاتورة_جديدة_حذف"]));
            }
            set {
                this["فاتورة_جديدة_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فاتورة_جديدة_طباعة {
            get {
                return ((bool)(this["فاتورة_جديدة_طباعة"]));
            }
            set {
                this["فاتورة_جديدة_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الفواتير_اضافه {
            get {
                return ((bool)(this["ادارة_الفواتير_اضافه"]));
            }
            set {
                this["ادارة_الفواتير_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الفواتير_تعديل {
            get {
                return ((bool)(this["ادارة_الفواتير_تعديل"]));
            }
            set {
                this["ادارة_الفواتير_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الفواتير_حذف {
            get {
                return ((bool)(this["ادارة_الفواتير_حذف"]));
            }
            set {
                this["ادارة_الفواتير_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الفواتير_طباعة {
            get {
                return ((bool)(this["ادارة_الفواتير_طباعة"]));
            }
            set {
                this["ادارة_الفواتير_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool العملاء_اضافه {
            get {
                return ((bool)(this["العملاء_اضافه"]));
            }
            set {
                this["العملاء_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool العملاء_تعديل {
            get {
                return ((bool)(this["العملاء_تعديل"]));
            }
            set {
                this["العملاء_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool العملاء_حذف {
            get {
                return ((bool)(this["العملاء_حذف"]));
            }
            set {
                this["العملاء_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool العملاء_طباعة {
            get {
                return ((bool)(this["العملاء_طباعة"]));
            }
            set {
                this["العملاء_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_المصروفات_اضافه {
            get {
                return ((bool)(this["ادارة_المصروفات_اضافه"]));
            }
            set {
                this["ادارة_المصروفات_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_المصروفات_تعديل {
            get {
                return ((bool)(this["ادارة_المصروفات_تعديل"]));
            }
            set {
                this["ادارة_المصروفات_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_المصروفات_حذف {
            get {
                return ((bool)(this["ادارة_المصروفات_حذف"]));
            }
            set {
                this["ادارة_المصروفات_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_المصروفات_طباعة {
            get {
                return ((bool)(this["ادارة_المصروفات_طباعة"]));
            }
            set {
                this["ادارة_المصروفات_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفروع_اضافه {
            get {
                return ((bool)(this["الفروع_اضافه"]));
            }
            set {
                this["الفروع_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفروع_تعديل {
            get {
                return ((bool)(this["الفروع_تعديل"]));
            }
            set {
                this["الفروع_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفروع_حذف {
            get {
                return ((bool)(this["الفروع_حذف"]));
            }
            set {
                this["الفروع_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفروع_طباعة {
            get {
                return ((bool)(this["الفروع_طباعة"]));
            }
            set {
                this["الفروع_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool مجموعات_المستخدمين_اضافه {
            get {
                return ((bool)(this["مجموعات_المستخدمين_اضافه"]));
            }
            set {
                this["مجموعات_المستخدمين_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool مجموعات_المستخدمين_تعديل {
            get {
                return ((bool)(this["مجموعات_المستخدمين_تعديل"]));
            }
            set {
                this["مجموعات_المستخدمين_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool مجموعات_المستخدمين_حذف {
            get {
                return ((bool)(this["مجموعات_المستخدمين_حذف"]));
            }
            set {
                this["مجموعات_المستخدمين_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool مجموعات_المستخدمين_طباعة {
            get {
                return ((bool)(this["مجموعات_المستخدمين_طباعة"]));
            }
            set {
                this["مجموعات_المستخدمين_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المستخدمين_اضافه {
            get {
                return ((bool)(this["المستخدمين_اضافه"]));
            }
            set {
                this["المستخدمين_اضافه"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المستخدمين_تعديل {
            get {
                return ((bool)(this["المستخدمين_تعديل"]));
            }
            set {
                this["المستخدمين_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المستخدمين_حذف {
            get {
                return ((bool)(this["المستخدمين_حذف"]));
            }
            set {
                this["المستخدمين_حذف"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المستخدمين_طباعة {
            get {
                return ((bool)(this["المستخدمين_طباعة"]));
            }
            set {
                this["المستخدمين_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool معلومات_الشركة_تعديل {
            get {
                return ((bool)(this["معلومات_الشركة_تعديل"]));
            }
            set {
                this["معلومات_الشركة_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الصلاحيات_تعديل {
            get {
                return ((bool)(this["ادارة_الصلاحيات_تعديل"]));
            }
            set {
                this["ادارة_الصلاحيات_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool معلومات_الشركة_طباعة {
            get {
                return ((bool)(this["معلومات_الشركة_طباعة"]));
            }
            set {
                this["معلومات_الشركة_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الصلاحيات_طباعة {
            get {
                return ((bool)(this["ادارة_الصلاحيات_طباعة"]));
            }
            set {
                this["ادارة_الصلاحيات_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الفواتير_اضافه_دفعة {
            get {
                return ((bool)(this["ادارة_الفواتير_اضافه_دفعة"]));
            }
            set {
                this["ادارة_الفواتير_اضافه_دفعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الفواتير_تعديل_دفعة {
            get {
                return ((bool)(this["ادارة_الفواتير_تعديل_دفعة"]));
            }
            set {
                this["ادارة_الفواتير_تعديل_دفعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الفواتير_حذف_دفعة {
            get {
                return ((bool)(this["ادارة_الفواتير_حذف_دفعة"]));
            }
            set {
                this["ادارة_الفواتير_حذف_دفعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ادارة_الفواتير_طباعة_دفعة {
            get {
                return ((bool)(this["ادارة_الفواتير_طباعة_دفعة"]));
            }
            set {
                this["ادارة_الفواتير_طباعة_دفعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ar-SA")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool التقرير_اليومي_طباعة {
            get {
                return ((bool)(this["التقرير_اليومي_طباعة"]));
            }
            set {
                this["التقرير_اليومي_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool التقرير_اليومي_PDF {
            get {
                return ((bool)(this["التقرير_اليومي_PDF"]));
            }
            set {
                this["التقرير_اليومي_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool التقرير_اليومي_اكسل {
            get {
                return ((bool)(this["التقرير_اليومي_اكسل"]));
            }
            set {
                this["التقرير_اليومي_اكسل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool التقرير_الشهري_طباعة {
            get {
                return ((bool)(this["التقرير_الشهري_طباعة"]));
            }
            set {
                this["التقرير_الشهري_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool التقرير_الشهري_PDF {
            get {
                return ((bool)(this["التقرير_الشهري_PDF"]));
            }
            set {
                this["التقرير_الشهري_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool التقرير_الشهري_اكسل {
            get {
                return ((bool)(this["التقرير_الشهري_اكسل"]));
            }
            set {
                this["التقرير_الشهري_اكسل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقرير_الفترة_طباعة {
            get {
                return ((bool)(this["تقرير_الفترة_طباعة"]));
            }
            set {
                this["تقرير_الفترة_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقرير_الفترة_PDF {
            get {
                return ((bool)(this["تقرير_الفترة_PDF"]));
            }
            set {
                this["تقرير_الفترة_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقرير_الفترة_اكسل {
            get {
                return ((bool)(this["تقرير_الفترة_اكسل"]));
            }
            set {
                this["تقرير_الفترة_اكسل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_للفترة_طباعة {
            get {
                return ((bool)(this["الفواتير_للفترة_طباعة"]));
            }
            set {
                this["الفواتير_للفترة_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_للفترة_PDF {
            get {
                return ((bool)(this["الفواتير_للفترة_PDF"]));
            }
            set {
                this["الفواتير_للفترة_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_للفترة_اكسل {
            get {
                return ((bool)(this["الفواتير_للفترة_اكسل"]));
            }
            set {
                this["الفواتير_للفترة_اكسل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_غير_المدفوعة_طباعة {
            get {
                return ((bool)(this["الفواتير_غير_المدفوعة_طباعة"]));
            }
            set {
                this["الفواتير_غير_المدفوعة_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_غير_المدفوعة_PDF {
            get {
                return ((bool)(this["الفواتير_غير_المدفوعة_PDF"]));
            }
            set {
                this["الفواتير_غير_المدفوعة_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_غير_المدفوعة_اكسل {
            get {
                return ((bool)(this["الفواتير_غير_المدفوعة_اكسل"]));
            }
            set {
                this["الفواتير_غير_المدفوعة_اكسل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_غير_المستلمة_طباعة {
            get {
                return ((bool)(this["الفواتير_غير_المستلمة_طباعة"]));
            }
            set {
                this["الفواتير_غير_المستلمة_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_غير_المستلمة_PDF {
            get {
                return ((bool)(this["الفواتير_غير_المستلمة_PDF"]));
            }
            set {
                this["الفواتير_غير_المستلمة_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_غير_المستلمة_اكسل {
            get {
                return ((bool)(this["الفواتير_غير_المستلمة_اكسل"]));
            }
            set {
                this["الفواتير_غير_المستلمة_اكسل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_غير_المدفوعة {
            get {
                return ((bool)(this["الفواتير_غير_المدفوعة"]));
            }
            set {
                this["الفواتير_غير_المدفوعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool الفواتير_غير_المستلمة {
            get {
                return ((bool)(this["الفواتير_غير_المستلمة"]));
            }
            set {
                this["الفواتير_غير_المستلمة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool المصروفات_طباعة {
            get {
                return ((bool)(this["المصروفات_طباعة"]));
            }
            set {
                this["المصروفات_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool المصروفات_PDF {
            get {
                return ((bool)(this["المصروفات_PDF"]));
            }
            set {
                this["المصروفات_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool المصروفات_اكسل {
            get {
                return ((bool)(this["المصروفات_اكسل"]));
            }
            set {
                this["المصروفات_اكسل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقرير_الانواع {
            get {
                return ((bool)(this["تقرير_الانواع"]));
            }
            set {
                this["تقرير_الانواع"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقرير_الانواع_طباعة {
            get {
                return ((bool)(this["تقرير_الانواع_طباعة"]));
            }
            set {
                this["تقرير_الانواع_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقرير_الانواع_PDF {
            get {
                return ((bool)(this["تقرير_الانواع_PDF"]));
            }
            set {
                this["تقرير_الانواع_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقرير_الانواع_اكسل {
            get {
                return ((bool)(this["تقرير_الانواع_اكسل"]));
            }
            set {
                this["تقرير_الانواع_اكسل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فواتير_العملاء {
            get {
                return ((bool)(this["فواتير_العملاء"]));
            }
            set {
                this["فواتير_العملاء"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فواتير_العملاء_طباعة {
            get {
                return ((bool)(this["فواتير_العملاء_طباعة"]));
            }
            set {
                this["فواتير_العملاء_طباعة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فواتير_العملاء_اكسل {
            get {
                return ((bool)(this["فواتير_العملاء_اكسل"]));
            }
            set {
                this["فواتير_العملاء_اكسل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool فواتير_العملاء_PDF {
            get {
                return ((bool)(this["فواتير_العملاء_PDF"]));
            }
            set {
                this["فواتير_العملاء_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool بيانات_العمال {
            get {
                return ((bool)(this["بيانات_العمال"]));
            }
            set {
                this["بيانات_العمال"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool اعدادات_الاتصال_تعديل {
            get {
                return ((bool)(this["اعدادات_الاتصال_تعديل"]));
            }
            set {
                this["اعدادات_الاتصال_تعديل"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool بيانات_المعلمين {
            get {
                return ((bool)(this["بيانات_المعلمين"]));
            }
            set {
                this["بيانات_المعلمين"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقارير_ضريبة_القيمة_المضافة {
            get {
                return ((bool)(this["تقارير_ضريبة_القيمة_المضافة"]));
            }
            set {
                this["تقارير_ضريبة_القيمة_المضافة"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool تقارير_حسابات_الموردين {
            get {
                return ((bool)(this["تقارير_حسابات_الموردين"]));
            }
            set {
                this["تقارير_حسابات_الموردين"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Remember_me {
            get {
                return ((bool)(this["Remember_me"]));
            }
            set {
                this["Remember_me"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RememberUserName {
            get {
                return ((string)(this["RememberUserName"]));
            }
            set {
                this["RememberUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short RememberBranch {
            get {
                return ((short)(this["RememberBranch"]));
            }
            set {
                this["RememberBranch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RememberLang {
            get {
                return ((string)(this["RememberLang"]));
            }
            set {
                this["RememberLang"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RememberPassword {
            get {
                return ((string)(this["RememberPassword"]));
            }
            set {
                this["RememberPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZatcaAutoReport {
            get {
                return ((bool)(this["ZatcaAutoReport"]));
            }
            set {
                this["ZatcaAutoReport"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_activated {
            get {
                return ((bool)(this["is_activated"]));
            }
            set {
                this["is_activated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SMS_Message {
            get {
                return ((string)(this["SMS_Message"]));
            }
            set {
                this["SMS_Message"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC-PC\\AASIM;Initial Catalog=DBT_SH;Integrated Security=True")]
        public string DBT_SHConnectionString {
            get {
                return ((string)(this["DBT_SHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC-PC\\AASIM;Initial Catalog=DBT_SH2;Integrated Security=True")]
        public string DBT_SH2ConnectionString {
            get {
                return ((string)(this["DBT_SH2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=DBTSH2;Integrated Security=True")]
        public string DBTSH2ConnectionString {
            get {
                return ((string)(this["DBTSH2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=DBT_SH22;Integrated Security=True")]
        public string DBT_SH22ConnectionString {
            get {
                return ((string)(this["DBT_SH22ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2T7M24S\\SQL2019;Initial Catalog=DBTSH2;Integrated Security=Tr" +
            "ue")]
        public string DBTSH2ConnectionString1 {
            get {
                return ((string)(this["DBTSH2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2T7M24S\\SQL2019;Initial Catalog=SewingSystem2;Integrated Secu" +
            "rity=True")]
        public string SewingSystem2ConnectionString {
            get {
                return ((string)(this["SewingSystem2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string accConFlag {
            get {
                return ((string)(this["accConFlag"]));
            }
            set {
                this["accConFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string accConVal {
            get {
                return ((string)(this["accConVal"]));
            }
            set {
                this["accConVal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime accConDt {
            get {
                return ((global::System.DateTime)(this["accConDt"]));
            }
            set {
                this["accConDt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BackupFrequencyDays {
            get {
                return ((int)(this["BackupFrequencyDays"]));
            }
            set {
                this["BackupFrequencyDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int BackupFrequencyHours {
            get {
                return ((int)(this["BackupFrequencyHours"]));
            }
            set {
                this["BackupFrequencyHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupPath {
            get {
                return ((string)(this["BackupPath"]));
            }
            set {
                this["BackupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1990-01-01")]
        public global::System.DateTime LastBackupTime {
            get {
                return ((global::System.DateTime)(this["LastBackupTime"]));
            }
            set {
                this["LastBackupTime"] = value;
            }
        }
    }
}
