//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranches
    {
        public tblBranches()
        {
            this.tblAlkbak = new HashSet<tblAlkbak>();
            this.tblAl_Qallab = new HashSet<tblAl_Qallab>();
            this.tblcategories = new HashSet<tblcategories>();
            this.tblcominfo = new HashSet<tblcominfo>();
            this.tblcustomers = new HashSet<tblcustomers>();
            this.tblfactories = new HashSet<tblfactories>();
            this.tblFrontPacket = new HashSet<tblFrontPacket>();
            this.tblInvoTafseel = new HashSet<tblInvoTafseel>();
            this.tblInvoTafseelDetail = new HashSet<tblInvoTafseelDetail>();
            this.tblinvpura = new HashSet<tblinvpura>();
            this.tblinvpurb = new HashSet<tblinvpurb>();
            this.tblitems = new HashSet<tblitems>();
            this.tblJabzur = new HashSet<tblJabzur>();
            this.tblpayments = new HashSet<tblpayments>();
            this.tblPermissions = new HashSet<tblPermissions>();
            this.tblresources = new HashSet<tblresources>();
            this.tblsanadm = new HashSet<tblsanadm>();
            this.tblsanads = new HashSet<tblsanads>();
            this.tblsettings = new HashSet<tblsettings>();
            this.tblSidePacket = new HashSet<tblSidePacket>();
            this.tbltailors = new HashSet<tbltailors>();
            this.tblUserGroup = new HashSet<tblUserGroup>();
            this.tblUsers = new HashSet<tblUsers>();
        }
    
        public long ID { get; set; }
        public string TheNameAr { get; set; }
        public string TheNameEn { get; set; }
        public string TheAddressAr { get; set; }
        public string TheAddressEn { get; set; }
        public string ThePhone1 { get; set; }
        public string ThePhone2 { get; set; }
        public string TheEmail { get; set; }
        public string TheTaxNo { get; set; }
        public byte[] TheLogo { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual ICollection<tblAlkbak> tblAlkbak { get; set; }
        public virtual ICollection<tblAl_Qallab> tblAl_Qallab { get; set; }
        public virtual ICollection<tblcategories> tblcategories { get; set; }
        public virtual ICollection<tblcominfo> tblcominfo { get; set; }
        public virtual ICollection<tblcustomers> tblcustomers { get; set; }
        public virtual ICollection<tblfactories> tblfactories { get; set; }
        public virtual ICollection<tblFrontPacket> tblFrontPacket { get; set; }
        public virtual ICollection<tblInvoTafseel> tblInvoTafseel { get; set; }
        public virtual ICollection<tblInvoTafseelDetail> tblInvoTafseelDetail { get; set; }
        public virtual ICollection<tblinvpura> tblinvpura { get; set; }
        public virtual ICollection<tblinvpurb> tblinvpurb { get; set; }
        public virtual ICollection<tblitems> tblitems { get; set; }
        public virtual ICollection<tblJabzur> tblJabzur { get; set; }
        public virtual ICollection<tblpayments> tblpayments { get; set; }
        public virtual ICollection<tblPermissions> tblPermissions { get; set; }
        public virtual ICollection<tblresources> tblresources { get; set; }
        public virtual ICollection<tblsanadm> tblsanadm { get; set; }
        public virtual ICollection<tblsanads> tblsanads { get; set; }
        public virtual ICollection<tblsettings> tblsettings { get; set; }
        public virtual ICollection<tblSidePacket> tblSidePacket { get; set; }
        public virtual ICollection<tbltailors> tbltailors { get; set; }
        public virtual ICollection<tblUserGroup> tblUserGroup { get; set; }
        public virtual ICollection<tblUsers> tblUsers { get; set; }
    }
}
