//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustomers
    {
        public tblcustomers()
        {
            this.tblInvoTafseel = new HashSet<tblInvoTafseel>();
            this.tblpayments = new HashSet<tblpayments>();
        }
    
        public long ID { get; set; }
        public string TheName { get; set; }
        public string ThePhone1 { get; set; }
        public string ThePhone2 { get; set; }
        public string TheEmail { get; set; }
        public Nullable<decimal> s1 { get; set; }
        public Nullable<decimal> s2 { get; set; }
        public Nullable<decimal> s3 { get; set; }
        public Nullable<decimal> s4 { get; set; }
        public Nullable<decimal> s5 { get; set; }
        public Nullable<decimal> s6 { get; set; }
        public Nullable<decimal> s7 { get; set; }
        public Nullable<decimal> s8 { get; set; }
        public Nullable<decimal> s9 { get; set; }
        public Nullable<decimal> s10 { get; set; }
        public Nullable<decimal> s11 { get; set; }
        public Nullable<decimal> s12 { get; set; }
        public Nullable<decimal> s13 { get; set; }
        public Nullable<decimal> s14 { get; set; }
        public Nullable<decimal> s15 { get; set; }
        public Nullable<decimal> s16 { get; set; }
        public Nullable<decimal> s17 { get; set; }
        public Nullable<decimal> s18 { get; set; }
        public Nullable<decimal> s19 { get; set; }
        public Nullable<decimal> s20 { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual tblBranches tblBranches { get; set; }
        public virtual tblUsers tblUsers { get; set; }
        public virtual ICollection<tblInvoTafseel> tblInvoTafseel { get; set; }
        public virtual ICollection<tblpayments> tblpayments { get; set; }
    }
}
