//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcominfo
    {
        public long ID { get; set; }
        public string TheNameAr { get; set; }
        public string TheNameEn { get; set; }
        public string TheAddressAr { get; set; }
        public string TheAddressEn { get; set; }
        public string ThePhone1 { get; set; }
        public string ThePhone2 { get; set; }
        public string TheEmail { get; set; }
        public string TheSite { get; set; }
        public byte[] TheLogo { get; set; }
        public Nullable<long> TheTax { get; set; }
        public string TheTaxRec { get; set; }
        public string TheTradeRec { get; set; }
        public string TheRoom { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual tblBranches tblBranches { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
