//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvpura
    {
        public tblinvpura()
        {
            this.tblinvpurb = new HashSet<tblinvpurb>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ResoID { get; set; }
        public Nullable<System.DateTime> TheDate { get; set; }
        public string TheDetails { get; set; }
        public Nullable<decimal> TheTotal1 { get; set; }
        public Nullable<decimal> TheDiscount { get; set; }
        public Nullable<decimal> TheTotal2 { get; set; }
        public Nullable<decimal> TheTax { get; set; }
        public Nullable<decimal> TheSafy { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual tblBranches tblBranches { get; set; }
        public virtual tblresources tblresources { get; set; }
        public virtual tblUsers tblUsers { get; set; }
        public virtual ICollection<tblinvpurb> tblinvpurb { get; set; }
    }
}
