//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvpurb
    {
        public long ID { get; set; }
        public Nullable<long> InvID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<decimal> TheQuanYard { get; set; }
        public Nullable<decimal> TheQuanMeter { get; set; }
        public string TheSaleUnit { get; set; }
        public Nullable<decimal> ThePrice { get; set; }
        public Nullable<decimal> TheTotal { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual tblBranches tblBranches { get; set; }
        public virtual tblinvpura tblinvpura { get; set; }
        public virtual tblitems tblitems { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
