//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoTafseel
    {
        public tblInvoTafseel()
        {
            this.tblInvoTafseelDetail = new HashSet<tblInvoTafseelDetail>();
        }
    
        public long ID { get; set; }
        public Nullable<long> InvoID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<System.DateTime> TheInvoDate { get; set; }
        public Nullable<System.DateTime> TheDeliveryDate { get; set; }
        public Nullable<decimal> InvoValue { get; set; }
        public Nullable<decimal> TheQuan { get; set; }
        public Nullable<decimal> TheTotal { get; set; }
        public Nullable<decimal> ThePaid { get; set; }
        public Nullable<decimal> TheDiscount { get; set; }
        public Nullable<decimal> TheDiscountPercent { get; set; }
        public Nullable<decimal> TheSafi { get; set; }
        public Nullable<decimal> TheTax { get; set; }
        public Nullable<decimal> TheRemain { get; set; }
        public string ThePayType { get; set; }
        public Nullable<long> InvoReferenceNum { get; set; }
        public string TheStatus { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual tblBranches tblBranches { get; set; }
        public virtual tblcustomers tblcustomers { get; set; }
        public virtual tblUsers tblUsers { get; set; }
        public virtual ICollection<tblInvoTafseelDetail> tblInvoTafseelDetail { get; set; }
    }
}
