//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoTafseelDetail
    {
        public long ID { get; set; }
        public Nullable<long> InvoID { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
        public string F12 { get; set; }
        public string F13 { get; set; }
        public string F14 { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
        public string F18 { get; set; }
        public string F19 { get; set; }
        public string F20 { get; set; }
        public string TafseelType { get; set; }
        public string TailorType { get; set; }
        public Nullable<long> FactoryID { get; set; }
        public Nullable<long> TailorID { get; set; }
        public Nullable<long> CatID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<decimal> ThePrice { get; set; }
        public Nullable<decimal> TheQuanFromStock { get; set; }
        public Nullable<decimal> TheNumClothes { get; set; }
        public Nullable<decimal> TheTotal { get; set; }
        public Nullable<long> JabzurID { get; set; }
        public Nullable<long> FrontPacketID { get; set; }
        public Nullable<long> SidePacketID { get; set; }
        public Nullable<long> Al_QallabID { get; set; }
        public Nullable<long> AlkbakID { get; set; }
        public string JabzurValue { get; set; }
        public string FrontPacketValue { get; set; }
        public string SidePacketValue { get; set; }
        public string Al_QallabValue { get; set; }
        public string AlkbakValue { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual tblAlkbak tblAlkbak { get; set; }
        public virtual tblAl_Qallab tblAl_Qallab { get; set; }
        public virtual tblBranches tblBranches { get; set; }
        public virtual tblcategories tblcategories { get; set; }
        public virtual tblfactories tblfactories { get; set; }
        public virtual tblFrontPacket tblFrontPacket { get; set; }
        public virtual tblInvoTafseel tblInvoTafseel { get; set; }
        public virtual tblitems tblitems { get; set; }
        public virtual tblJabzur tblJabzur { get; set; }
        public virtual tblSidePacket tblSidePacket { get; set; }
        public virtual tbltailors tbltailors { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
