//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJabzur
    {
        public tblJabzur()
        {
            this.tblInvoTafseelDetail = new HashSet<tblInvoTafseelDetail>();
        }
    
        public long ID { get; set; }
        public string TheName { get; set; }
        public string TheDefaultValue { get; set; }
        public byte[] TheImage { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual tblBranches tblBranches { get; set; }
        public virtual ICollection<tblInvoTafseelDetail> tblInvoTafseelDetail { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
