//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermissions
    {
        public tblPermissions()
        {
            this.tblPermissions1 = new HashSet<tblPermissions>();
        }
    
        public long ID { get; set; }
        public Nullable<long> UserGroupID { get; set; }
        public string ObjectName { get; set; }
        public string PermissionName { get; set; }
        public Nullable<bool> TheValues { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
    
        public virtual tblBranches tblBranches { get; set; }
        public virtual ICollection<tblPermissions> tblPermissions1 { get; set; }
        public virtual tblPermissions tblPermissions2 { get; set; }
        public virtual tblUserGroup tblUserGroup { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
