//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsanadm
    {
        public long ID { get; set; }
        public string SanadID { get; set; }
        public string TheName { get; set; }
        public Nullable<System.DateTime> TheDate { get; set; }
        public string TheDetails { get; set; }
        public Nullable<decimal> TheAmount { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual tblBranches tblBranches { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
