//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserGroup
    {
        public tblUserGroup()
        {
            this.tblPermissions = new HashSet<tblPermissions>();
            this.tblUsers1 = new HashSet<tblUsers>();
        }
    
        public long ID { get; set; }
        public string UserGroupName { get; set; }
        public string Notes { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<long> BranchID { get; set; }
    
        public virtual tblBranches tblBranches { get; set; }
        public virtual ICollection<tblPermissions> tblPermissions { get; set; }
        public virtual tblUsers tblUsers { get; set; }
        public virtual ICollection<tblUsers> tblUsers1 { get; set; }
    }
}
